service:
  name: rosenda-schedule

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: "us-east-1"
  environment:
    SCHEDULE_TABLE_NAME: ${self:custom.ScheduleTable.name}
    SECRET: ${file(secret.pem)}
  iamRoleStatements:
    - ${file(iam/ScheduleTableIAM.yml):ScheduleTableIAM}

resources:
  Resources:
    ScheduleTable: ${file(resources/ScheduleTable.yml):ScheduleTable}

functions:
  schedule:
    handler: src/handlers/schedule.handler
    events:
      - http:
          method: POST
          path: /schedule
          cors: true

  getSchedule:
    handler: src/handlers/getSchedule.handler
    events:
      - http:
          method: GET
          path: /schedule
          cors: true

  getScheduleById:
    handler: src/handlers/getScheduleById.handler
    events:
      - http:
          method: GET
          path: /schedule/{id}
          cors: true

custom:
  ScheduleTable:
    name: !Ref ScheduleTable
    arn: !GetAtt ScheduleTable.Arn
